-- Add sample appointments with real St. Paul area addresses
-- Using specific user_id: 55daefad-b5f8-43bb-ad1e-0b07e0688237

INSERT INTO appointments (
    user_id,
    customer_name,
    customer_email,
    customer_phone,
    service_type,
    appointment_date,
    appointment_time,
    status,
    service_address,
    service_city,
    service_state,
    service_zip,
    service_description,
    service_category,
    special_instructions,
    estimated_duration,
    duration_minutes,
    urgency_level,
    created_at
) VALUES
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Sarah Johnson',
        'sarah.johnson@email.com',
        '+1 (555) 234-5678',
        'HVAC Maintenance',
        NOW() + INTERVAL '2 days',
        '09:00:00',
        'scheduled',
        '123 Summit Ave',
        'St Paul',
        'MN',
        '55102',
        'Routine HVAC maintenance check - strange noise from unit',
        'Maintenance',
        'Dog in backyard - please call before entering',
        '1-2 hours',
        90,
        'medium',
        NOW() - INTERVAL '2 hours'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Michael Chen',
        'michael.chen@email.com',
        '+1 (555) 876-5432',
        'Emergency Heating Repair',
        NOW() + INTERVAL '4 hours',
        '14:00:00',
        'scheduled',
        '456 Grand Ave',
        'St Paul',
        'MN',
        '55105',
        'Complete heating system failure - emergency service',
        'Emergency',
        'Commercial building - meet at main entrance',
        '2-3 hours',
        150,
        'high',
        NOW() - INTERVAL '30 minutes'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Lisa Martinez',
        'lisa.martinez@email.com',
        '+1 (555) 432-1098',
        'AC Repair',
        NOW() + INTERVAL '1 day',
        '10:00:00',
        'scheduled',
        '789 Selby Ave',
        'St Paul',
        'MN',
        '55104',
        'Air conditioning not cooling properly - needs diagnosis',
        'Repair',
        'Parking in rear',
        '1-2 hours',
        90,
        'high',
        NOW() - INTERVAL '3 hours'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Jennifer Lee',
        'jennifer.lee@email.com',
        '+1 (555) 567-8901',
        'Water Leak Emergency',
        NOW() - INTERVAL '30 minutes',
        '13:30:00',
        'completed',
        '321 Marshall Ave',
        'St Paul',
        'MN',
        '55102',
        'Water leak near HVAC unit - emergency repair',
        'Emergency',
        'Code 1234 for building access',
        '2-3 hours',
        180,
        'high',
        NOW() - INTERVAL '1 hour'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'James Brown',
        'james.brown@email.com',
        '+1 (555) 890-1234',
        'Commercial Maintenance',
        NOW() + INTERVAL '1 week',
        '08:00:00',
        'scheduled',
        '567 University Ave W',
        'St Paul',
        'MN',
        '55103',
        'Preventive maintenance for multiple HVAC units',
        'Maintenance',
        'Large commercial building - multiple units on roof',
        '4-5 hours',
        270,
        'medium',
        NOW() - INTERVAL '2 days'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Maria Gonzales',
        'maria.gonzales@email.com',
        '+1 (555) 111-2222',
        'Annual HVAC Inspection',
        NOW() + INTERVAL '5 days',
        '11:00:00',
        'scheduled',
        '890 Randolph Ave',
        'St Paul',
        'MN',
        '55102',
        'Annual HVAC system inspection - returning customer',
        'Inspection',
        'Keys with neighbor at 892 Randolph',
        '1-2 hours',
        90,
        'medium',
        NOW() - INTERVAL '8 hours'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Kevin O''Brien',
        'kevin.obrien@email.com',
        '+1 (555) 333-4444',
        'Commercial Freezer Repair',
        NOW() + INTERVAL '2 hours',
        '15:00:00',
        'scheduled',
        '234 West 7th St',
        'St Paul',
        'MN',
        '55102',
        'Commercial freezer unit failure - restaurant',
        'Emergency',
        'Enter through kitchen entrance - ask for Kevin',
        '2-4 hours',
        180,
        'high',
        NOW() - INTERVAL '1 hour'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Patricia Williams',
        'patricia.williams@email.com',
        '+1 (555) 444-5555',
        'Furnace Installation',
        NOW() + INTERVAL '3 days',
        '08:30:00',
        'scheduled',
        '678 Payne Ave',
        'St Paul',
        'MN',
        '55130',
        'New furnace installation - old unit completely failed',
        'Installation',
        'Basement access - stairs narrow',
        '4-6 hours',
        300,
        'medium',
        NOW() - INTERVAL '1 day'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Robert Anderson',
        'robert.anderson@email.com',
        '+1 (555) 666-7777',
        'Duct Cleaning',
        NOW() + INTERVAL '1 week',
        '09:30:00',
        'scheduled',
        '432 Como Ave',
        'St Paul',
        'MN',
        '55103',
        'Full duct cleaning service for residential property',
        'Cleaning',
        'Two-story home - all vents accessible',
        '3-4 hours',
        210,
        'low',
        NOW() - INTERVAL '3 days'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Linda Thompson',
        'linda.thompson@email.com',
        '+1 (555) 777-8888',
        'Thermostat Upgrade',
        NOW() + INTERVAL '4 days',
        '13:00:00',
        'scheduled',
        '156 Dale St N',
        'St Paul',
        'MN',
        '55104',
        'Smart thermostat installation and programming',
        'Installation',
        'WiFi password: StPaul2024',
        '1 hour',
        60,
        'low',
        NOW() - INTERVAL '5 hours'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Thomas Martinez',
        'thomas.martinez@email.com',
        '+1 (555) 888-9999',
        'AC Unit Replacement',
        NOW() + INTERVAL '2 weeks',
        '07:30:00',
        'scheduled',
        '789 Maryland Ave E',
        'St Paul',
        'MN',
        '55106',
        'Replace aging AC unit with energy-efficient model',
        'Installation',
        'Crane needed for rooftop unit - coordinated with building',
        '6-8 hours',
        420,
        'medium',
        NOW() - INTERVAL '1 week'
    ),
    (
        '55daefad-b5f8-43bb-ad1e-0b07e0688237',
        'Nancy Wilson',
        'nancy.wilson@email.com',
        '+1 (555) 999-0000',
        'Heat Pump Service',
        NOW() - INTERVAL '2 days',
        '10:30:00',
        'completed',
        '234 Snelling Ave N',
        'St Paul',
        'MN',
        '55104',
        'Heat pump seasonal maintenance and check',
        'Maintenance',
        'Gate code 5678',
        '1-2 hours',
        90,
        'low',
        NOW() - INTERVAL '3 days'
    );
